#!/usr/bin/env bash

set -eu

SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd)

files=$(find "$SCRIPT_DIR/in" -type f)
for file in $files; do
  if [[ "$file" =~ .gitconfig.in$ ]]; then
    if [[ -z ${GIT_USERNAME:-} ]]; then
      read -rp "Enter your git user name: " GIT_USERNAME
    fi
    if [[ -z ${GIT_EMAIL:-} ]]; then
      read -rp "Enter your git email: " GIT_EMAIL
    fi
    sed -e "s|@USERNAME@|$GIT_USERNAME|g" -e "s|@USEREMAIL@|$GIT_EMAIL|g" "$file" > "$SCRIPT_DIR/link/.gitconfig"
  elif [[ "$file" =~ .github-cli/aliases.yml$ ]]; then
    # if gh command is installed, set up alias
    if command -v gh > /dev/null; then
      gh alias import "$file"
    fi
  elif [[ "$file" =~ .vscode/settings.json.in$ ]]; then
    dest="$SCRIPT_DIR/link/.vscode-server/data/Machine/settings.json"
    mkdir -p "$(dirname "$dest")"
    sed -e "s|@HOME@|$HOME|g" "$file" > "$dest"
  else
    echo "Unknown file $file. skip it"
  fi
done

