#!/usr/bin/env bash

set -eu

SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd)

show_help() {
	echo "Usage: $0 [options]"
	echo "Options:"
	echo "  -y, --yes           Answer yes to all questions"
	echo "  --help              Show this help message"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
	arg="$1"
	case $arg in
	-y|--yes)
		YES=1
		shift
		;;
	--help)
		show_help
		exit 0
		;;
	*)
		echo "Unknown option: $arg"
		show_help
		exit 1
		;;
	esac
done

# Download git completion and prompt scripts
if type curl > /dev/null; then
	fetch="curl -LO"
elif type wget > /dev/null; then
	fetch="wget -nc"
else
	echo "Please install wget or curl"
	exit 1
fi
GITDIR="$SCRIPT_DIR/in/.config/git"
cd "$GITDIR"
HASH=c032b1d8bc29de4fb1322d841d8216ca961dcb53
BASE="https://raw.githubusercontent.com/git/git/$HASH/contrib/completion"
$fetch "$BASE/git-completion.bash"
$fetch "$BASE/git-prompt.sh"
sha512sum -c sha512-checksum.txt
cd "$SCRIPT_DIR"

files=$(find "$SCRIPT_DIR/in" -type f)
for file in $files; do
	if [[ "$file" =~ .gitconfig.in$ ]]; then
		if [[ -z ${GIT_USERNAME:-} ]]; then
			read -rp "Enter your git user name: " GIT_USERNAME
		fi
		if [[ -z ${GIT_EMAIL:-} ]]; then
			read -rp "Enter your git email: " GIT_EMAIL
		fi
		sed -e "s|@USERNAME@|$GIT_USERNAME|g" -e "s|@USEREMAIL@|$GIT_EMAIL|g" "$file" > "$SCRIPT_DIR/link/.gitconfig"
	elif [[ "$file" =~ .github-cli/aliases.yml$ ]]; then
		# if gh command is installed, set up alias
		if command -v gh > /dev/null; then
			gh alias import "$file"
		fi
	elif [[ "$file" =~ .vscode/settings.json.in$ ]]; then
		dest="$SCRIPT_DIR/link/.vscode-server/data/Machine/settings.json"
		mkdir -p "$(dirname "$dest")"
		sed -e "s|@HOME@|$HOME|g" "$file" > "$dest"
	elif [[ "$file" =~ .config/git/git-.+$ ]]; then
		dest="$SCRIPT_DIR/link/.config/git"
		mkdir -p "$dest"
		cp "$file" "$dest"
		echo "Copied $file to $dest"
	elif [[ "$file" =~ .config/git/sha512-checksum.txt$ ]]; then
		echo "Skipping $file"
	else
		echo "Unknown file $file. skip it"
	fi
done

