#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
LINK_DIR="$SCRIPT_DIR/link"

all_files=$(find "$LINK_DIR" -type f)
for file in $all_files; do
  relative_path=${file#"$LINK_DIR"/}
  dest="$HOME/$relative_path"
  mkdir -p "$(dirname "$dest")"
  echo "ln -sf $file $dest"
  ln -sf "$file" "$dest"
done

# ~/.local/share/vim-lsp-settings/servers/pylsp-all/venv/bin/pip installl pylsp-mypy pylsp-black
