name: dotfiles-test

on:
  push:
    paths-ignore:
      - ".gitignore"
      - "README.md"
      - "LICENSE"

jobs:
  test-linux:
    timeout-minutes: 5 # Max execution time (min)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pre-setup
        run: GIT_USERNAME="test user" GIT_EMAIL="example@example.com" ./pre-setup -y
      - name: setup
        run: ./setup
